version: '3.8'

services:
    nginx:
        restart: always
        container_name: ${APP_NAME}-nginx
        build:
            context: docker
            dockerfile: development/nginx/Dockerfile
        ports:
            - "8073:80"
        volumes:
            - ./project:/project
        depends_on:
            - php-fpm
            - php-cli
        networks:
            - laravel-server

    node-cli:
        container_name: ${APP_NAME}-node-cli
        build:
            context: docker
            dockerfile: development/node-cli/Dockerfile
        volumes:
            - ./project:/project
        networks:
            - laravel-server

    mailer:
        image: schickling/mailcatcher
        container_name: ${APP_NAME}-mailer
        ports:
            - "1073:1080"
        networks:
            - laravel-server

    php-fpm:
        container_name: ${APP_NAME}-php-fpm
        build:
            context: docker
            dockerfile: development/php-fpm/Dockerfile
        ports:
            - "9001:9000"
        volumes:
            - ./project:/project
        depends_on:
            - maria-db
        networks:
            - laravel-server

    php-cli:
        container_name: ${APP_NAME}-php-cli
        build:
            context: docker
            dockerfile: development/php-cli/Dockerfile
        restart: always
        volumes:
            - ./project:/project
        networks:
            - laravel-server

    maria-db:
        restart: always
        image: mariadb:11.1.3
        container_name: ${APP_NAME}-db
        volumes:
            - ./volumes/database/mysql://var/lib/mysql
        ports:
            - "3373:3306"
        command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]
        environment:
            - MYSQL_PASSWORD=${DATABASE_PASSWORD}
            - MYSQL_USER=${DATABASE_USER}
            - MYSQL_DATABASE=${DATABASE_NAME}
            - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
        networks:
            - laravel-server
            - laravel-network

networks:
    laravel-server:
        external: true
    laravel-network:
        external: true
